kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-leases-role
  labels:
    # pipeline SA in OpenShift automatically gets edit rights so aggregating this role
    # enables pipeline to work with lease without having to explicitly create a rolebinding
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
    - demo.redhat.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - patch
      - delete
      - watch
      - list