apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leases.demo.redhat.io
spec:
  group: demo.redhat.io
  versions:
   - name: v1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         type: object
         properties:
           spec:
             type: object
             properties:
               owner:
                 type: string
               created:
                 type: string
  scope: Namespaced
  names:
    plural: leases
    singular: lease
    kind: Lease
    shortNames:
      - le
