apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: release-lease
spec:
  params:
  - name: lease-name
    type: string
  steps:
    - name: delete-lease
      image: linkyard/kubectl:1.14.2
      script: kubectl delete lease.demo.redhat.io/$(inputs.params.lease-name) --ignore-not-found=true